#!/usr/bin/env bash
# CivicRecords AI — Hardware Detection Script
# Detects AMD GPU/NPU capabilities and writes configuration to .env.hardware
# Called by install.sh before docker compose up


# NOTE: No set -euo pipefail — this is a detection script where partial results
# are acceptable. Individual probes use defensive fallbacks rather than aborting.

# ─── Hardware-floor constant (MIN_RAM_GB) ─────────────────────────────────────
# (a) What this value represents:
#     The minimum host RAM (in GB) required to run the full CivicSuite SERVER
#     stack — postgres + redis + ollama (gemma4:e4b loaded) + api + celery
#     worker + celery beat + frontend — on a single box that one or more
#     clerks access over the LAN via http://<server>:8080. The installer
#     refuses to proceed below this floor; both install.sh and install.ps1
#     gate on this number.
# (b) How it was derived:
#     It was NOT derived from measurement. It was inherited from the Tier 5
#     "target-profile baseline" (T5C, 2026-04-21) — the spec'd dev workstation
#     RAM that the picker logic was originally tuned against — and has been
#     carried forward as the installer gate without an independent peak-RAM
#     profile of the running stack.
# (c) Date set:
#     2026-05-14 (named-variable extraction; numeric value 32 inherited from
#     the 2026-04-21 T5C baseline).
# (d) Rationale / run-id:
#     pipeline-cw run 2026-05-14-1447-server-reframe extracted the literal
#     32 into MIN_RAM_GB and flagged it "needs measurement — arbitrary value
#     pending peak-RAM profile across postgres+redis+ollama+api+worker+beat+
#     frontend during ingestion + cited-answer query." When that profile lands
#     the value here should be revised against measured peak working-set
#     plus a documented safety margin, and the comment block updated
#     accordingly.
MIN_RAM_GB=32

# Allow callers (install.sh) to source THIS file just to import MIN_RAM_GB
# without running the detector. Setting HARDWARE_CONSTANTS_ONLY=1 returns
# early, before any echo, file write, or probe.
if [ "${HARDWARE_CONSTANTS_ONLY:-0}" = "1" ]; then
    return 0 2>/dev/null || exit 0
fi

HARDWARE_ENV_FILE=".env.hardware"
echo "# CivicRecords AI — Auto-detected hardware configuration" > "$HARDWARE_ENV_FILE"
echo "# Generated by scripts/detect_hardware.sh on $(date)" >> "$HARDWARE_ENV_FILE"

echo ""
echo "=== CivicRecords AI Hardware Detection ==="
echo ""

# ─── CPU Detection ───────────────────────────────────────────────────────────
CPU_MODEL=$(grep -m1 "model name" /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs 2>/dev/null || sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Unknown CPU")
echo "CPU: $CPU_MODEL"
echo "CIVICRECORDS_CPU_MODEL=\"$CPU_MODEL\"" >> "$HARDWARE_ENV_FILE"

PLATFORM="unknown"
NPU_TOPS=0

if echo "$CPU_MODEL" | grep -qiE "Ryzen AI (Max|MAX)"; then
    PLATFORM="strix_halo"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI Max (Strix Halo)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen AI [0-9]+ [0-9]+(HX|HS|U|H)"; then
    PLATFORM="strix_krackan"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI 300/400 (Strix Point / Gorgon Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 8[0-9]{3}"; then
    PLATFORM="hawk_point"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 8000 (Hawk Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 7[0-9]{3}(H|U|HS)"; then
    PLATFORM="phoenix"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 7000 Mobile (Phoenix)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen 9 (7945|8945)HX"; then
    PLATFORM="dragon_range"
    NPU_TOPS=0
    echo "Platform: AMD Ryzen Dragon Range (workstation mobile — no NPU, weak iGPU)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 9[0-9]{3}"; then
    PLATFORM="granite_ridge"
    NPU_TOPS=0
    echo "Platform: AMD Ryzen 9000 Desktop (Granite Ridge — no iGPU)"
else
    PLATFORM="unknown_amd"
    echo "Platform: Unknown AMD processor — defaulting to CPU inference"
fi

echo "CIVICRECORDS_PLATFORM=\"$PLATFORM\"" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_NPU_TOPS=$NPU_TOPS" >> "$HARDWARE_ENV_FILE"

# ─── GPU Detection via ROCm ───────────────────────────────────────────────────
GPU_ENABLED=false
GFX_VERSION=""
HSA_OVERRIDE=""
GPU_CU_COUNT=0

if command -v rocm-smi &>/dev/null || command -v rocminfo &>/dev/null; then
    echo ""
    echo "ROCm found — querying GPU..."

    if command -v rocminfo &>/dev/null; then
        GFX_RAW=$(rocminfo 2>/dev/null | grep -i "gfx" | grep -v "gfx_version" | head -1 | awk '{print $NF}' || true)
        echo "Detected GFX target: $GFX_RAW"
    fi

    case "$PLATFORM" in
        strix_halo)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.1"
            GPU_CU_COUNT=40
            ;;
        strix_krackan)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.1"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "0")
            GPU_CU_COUNT=${CU_DETECT:-16}
            if [ "$GPU_CU_COUNT" -le 12 ]; then
                GFX_VERSION="11.5.0"
                HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.0"
            fi
            ;;
        hawk_point|phoenix)
            GFX_VERSION="11.0.0"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.0.0"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "12")
            GPU_CU_COUNT=${CU_DETECT:-12}
            if [ "$GPU_CU_COUNT" -le 8 ]; then
                HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.0.2"
                GFX_VERSION="11.0.2"
            fi
            ;;
        dragon_range)
            echo "WARNING: Dragon Range iGPU (Radeon 610M, 2 CU) — not suitable for inference"
            echo "If a discrete GPU is present, ROCm will use it automatically"
            GPU_ENABLED=false
            ;;
        granite_ridge)
            echo "WARNING: No iGPU on Granite Ridge — CPU inference only unless discrete GPU present"
            GPU_ENABLED=false
            ;;
    esac

    if [ -e /dev/kfd ] && [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ]; then
        GPU_ENABLED=true
        echo "GPU accessible via /dev/kfd — ROCm GPU inference enabled"
        echo "GFX override: $HSA_OVERRIDE"
    else
        echo "WARNING: /dev/kfd not found — falling back to CPU inference"
        echo "Run: sudo usermod -aG render,video \$USER && reboot"
    fi
else
    echo "ROCm not installed — will use CPU inference"
    echo "For GPU acceleration, run: amdgpu-install --usecase=rocm"
fi

echo ""
echo "CIVICRECORDS_GPU_ENABLED=$GPU_ENABLED" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_GPU_CU_COUNT=$GPU_CU_COUNT" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_GFX_VERSION=\"$GFX_VERSION\"" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_HSA_OVERRIDE=\"$HSA_OVERRIDE\"" >> "$HARDWARE_ENV_FILE"

# ─── NPU Detection ────────────────────────────────────────────────────────────
NPU_AVAILABLE=false

if [ -e /dev/accel/accel0 ] || (lsmod 2>/dev/null | grep -q "amdxdna" 2>/dev/null); then
    NPU_AVAILABLE=true
    echo "NPU: XDNA driver detected — $NPU_TOPS TOPS available"
    echo "NOTE: Ollama does not currently use the NPU; reserved for future ONNX integration"
else
    echo "NPU: XDNA driver not loaded (install kernel 6.11+ and amdxdna driver for NPU access)"
fi

echo "CIVICRECORDS_NPU_AVAILABLE=$NPU_AVAILABLE" >> "$HARDWARE_ENV_FILE"

# ─── Memory Detection ─────────────────────────────────────────────────────────
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}' || echo "0")
if [ "$TOTAL_RAM_KB" -eq 0 ] 2>/dev/null; then
    # macOS fallback
    TOTAL_RAM_BYTES=$(sysctl -n hw.memsize 2>/dev/null || echo "0")
    TOTAL_RAM_GB=$((TOTAL_RAM_BYTES / 1024 / 1024 / 1024))
else
    TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))
fi
echo ""
echo "RAM: ${TOTAL_RAM_GB} GB total"

if [ "$TOTAL_RAM_GB" -lt "$MIN_RAM_GB" ]; then
    echo "ERROR: CivicRecords AI requires a minimum of ${MIN_RAM_GB} GB RAM (MIN_RAM_GB — see provenance block at top of this file). Found: ${TOTAL_RAM_GB} GB"
    echo "       No Gemma 4 tag is supportable below this floor. Aborting hardware gate."
    echo "       This matches scripts/detect_hardware.ps1 behavior on Windows (exits 1 below ${MIN_RAM_GB} GB)."
    exit 1
fi

# T5C (Tier 5 Blocker 1 resolution 2026-04-21): gemma4:e4b is the single truthful default
# across every runtime-config surface and the installer picker. The 4-model set the picker
# presents is {gemma4:e2b, gemma4:e4b, gemma4:26b, gemma4:31b}; e4b is the default.
# Only e2b and e4b are supportable at the 32 GB target-profile baseline; 26b and 31b
# are shown for operators with stronger hardware and must be selected explicitly.
RECOMMENDED_MODEL="gemma4:e4b"

echo "CIVICRECORDS_TOTAL_RAM_GB=$TOTAL_RAM_GB" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_RECOMMENDED_MODEL=\"$RECOMMENDED_MODEL\"" >> "$HARDWARE_ENV_FILE"

# ─── Disk Detection ───────────────────────────────────────────────────────────
DISK_FREE_GB=$(df -BG . 2>/dev/null | tail -1 | awk '{print $4}' | tr -d 'G' || df -g . 2>/dev/null | tail -1 | awk '{print $4}' || echo "0")
echo "Disk free: ${DISK_FREE_GB} GB on current volume"

if [ "$DISK_FREE_GB" -lt 50 ]; then
    echo "WARNING: Less than 50 GB free disk space. Minimum 50 GB recommended for model storage and document cache."
fi

echo "CIVICRECORDS_DISK_FREE_GB=$DISK_FREE_GB" >> "$HARDWARE_ENV_FILE"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "=== Detection Complete ==="
echo "Platform:        $PLATFORM"
echo "GPU Enabled:     $GPU_ENABLED"
if [ "$GPU_ENABLED" = true ]; then
    echo "GFX Override:    $HSA_OVERRIDE"
    echo "CU Count:        $GPU_CU_COUNT"
fi
echo "NPU Available:   $NPU_AVAILABLE (${NPU_TOPS} TOPS)"
echo "Recommended Model: $RECOMMENDED_MODEL"
echo ""
echo "Configuration written to $HARDWARE_ENV_FILE"
echo "This file will be merged into your Docker environment automatically."
