#!/usr/bin/env bash
# CivicRecords AI — Hardware Detection Script
# Detects AMD GPU/NPU capabilities and writes configuration to .env.hardware
# Called by install.sh before docker compose up

set -euo pipefail

HARDWARE_ENV_FILE=".env.hardware"
echo "# CivicRecords AI — Auto-detected hardware configuration" > "$HARDWARE_ENV_FILE"
echo "# Generated by scripts/detect_hardware.sh on $(date)" >> "$HARDWARE_ENV_FILE"

echo ""
echo "=== CivicRecords AI Hardware Detection ==="
echo ""

# ─── CPU Detection ───────────────────────────────────────────────────────────
CPU_MODEL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
echo "CPU: $CPU_MODEL"
echo "CIVICRECORDS_CPU_MODEL=\"$CPU_MODEL\"" >> "$HARDWARE_ENV_FILE"

PLATFORM="unknown"
NPU_TOPS=0

if echo "$CPU_MODEL" | grep -qiE "Ryzen AI (Max|MAX)"; then
    PLATFORM="strix_halo"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI Max (Strix Halo)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen AI [0-9]+ [0-9]+(HX|HS|U|H)"; then
    PLATFORM="strix_krackan"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI 300/400 (Strix Point / Gorgon Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 8[0-9]{3}"; then
    PLATFORM="hawk_point"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 8000 (Hawk Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 7[0-9]{3}(H|U|HS)"; then
    PLATFORM="phoenix"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 7000 Mobile (Phoenix)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen 9 (7945|8945)HX"; then
    PLATFORM="dragon_range"
    NPU_TOPS=0
    echo "Platform: AMD Ryzen Dragon Range (workstation mobile — no NPU, weak iGPU)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 9[0-9]{3}"; then
    PLATFORM="granite_ridge"
    NPU_TOPS=0
    echo "Platform: AMD Ryzen 9000 Desktop (Granite Ridge — no iGPU)"
else
    PLATFORM="unknown_amd"
    echo "Platform: Unknown AMD processor — defaulting to CPU inference"
fi

echo "CIVICRECORDS_PLATFORM=\"$PLATFORM\"" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_NPU_TOPS=$NPU_TOPS" >> "$HARDWARE_ENV_FILE"

# ─── GPU Detection via ROCm ───────────────────────────────────────────────────
GPU_ENABLED=false
GFX_VERSION=""
HSA_OVERRIDE=""
GPU_CU_COUNT=0

if command -v rocm-smi &>/dev/null || command -v rocminfo &>/dev/null; then
    echo ""
    echo "ROCm found — querying GPU..."

    if command -v rocminfo &>/dev/null; then
        GFX_RAW=$(rocminfo 2>/dev/null | grep -i "gfx" | grep -v "gfx_version" | head -1 | awk '{print $NF}' || true)
        echo "Detected GFX target: $GFX_RAW"
    fi

    case "$PLATFORM" in
        strix_halo)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.1"
            GPU_CU_COUNT=40
            ;;
        strix_krackan)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.1"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "0")
            GPU_CU_COUNT=${CU_DETECT:-16}
            if [ "$GPU_CU_COUNT" -le 12 ]; then
                GFX_VERSION="11.5.0"
                HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.5.0"
            fi
            ;;
        hawk_point|phoenix)
            GFX_VERSION="11.0.0"
            HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.0.0"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "12")
            GPU_CU_COUNT=${CU_DETECT:-12}
            if [ "$GPU_CU_COUNT" -le 8 ]; then
                HSA_OVERRIDE="HSA_OVERRIDE_GFX_VERSION=11.0.2"
                GFX_VERSION="11.0.2"
            fi
            ;;
        dragon_range)
            echo "WARNING: Dragon Range iGPU (Radeon 610M, 2 CU) — not suitable for inference"
            echo "If a discrete GPU is present, ROCm will use it automatically"
            GPU_ENABLED=false
            ;;
        granite_ridge)
            echo "WARNING: No iGPU on Granite Ridge — CPU inference only unless discrete GPU present"
            GPU_ENABLED=false
            ;;
    esac

    if [ -e /dev/kfd ] && [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ]; then
        GPU_ENABLED=true
        echo "GPU accessible via /dev/kfd — ROCm GPU inference enabled"
        echo "GFX override: $HSA_OVERRIDE"
    else
        echo "WARNING: /dev/kfd not found — falling back to CPU inference"
        echo "Run: sudo usermod -aG render,video \$USER && reboot"
    fi
else
    echo "ROCm not installed — will use CPU inference"
    echo "For GPU acceleration, run: amdgpu-install --usecase=rocm"
fi

echo ""
echo "CIVICRECORDS_GPU_ENABLED=$GPU_ENABLED" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_GPU_CU_COUNT=$GPU_CU_COUNT" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_GFX_VERSION=\"$GFX_VERSION\"" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_HSA_OVERRIDE=\"$HSA_OVERRIDE\"" >> "$HARDWARE_ENV_FILE"

# ─── NPU Detection ────────────────────────────────────────────────────────────
NPU_AVAILABLE=false

if [ -e /dev/accel/accel0 ] || lsmod 2>/dev/null | grep -q "amdxdna"; then
    NPU_AVAILABLE=true
    echo "NPU: XDNA driver detected — $NPU_TOPS TOPS available"
    echo "NOTE: Ollama does not currently use the NPU; reserved for future ONNX integration"
else
    echo "NPU: XDNA driver not loaded (install kernel 6.11+ and amdxdna driver for NPU access)"
fi

echo "CIVICRECORDS_NPU_AVAILABLE=$NPU_AVAILABLE" >> "$HARDWARE_ENV_FILE"

# ─── Memory Detection ─────────────────────────────────────────────────────────
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))
echo ""
echo "RAM: ${TOTAL_RAM_GB} GB total"

if [ "$TOTAL_RAM_GB" -lt 32 ]; then
    echo "ERROR: CivicRecords AI requires a minimum of 32 GB RAM. Found: ${TOTAL_RAM_GB} GB"
    exit 1
fi

RECOMMENDED_MODEL="gemma4:12b"
if [ "$TOTAL_RAM_GB" -ge 48 ]; then
    RECOMMENDED_MODEL="gemma4:27b"
fi

echo "CIVICRECORDS_TOTAL_RAM_GB=$TOTAL_RAM_GB" >> "$HARDWARE_ENV_FILE"
echo "CIVICRECORDS_RECOMMENDED_MODEL=\"$RECOMMENDED_MODEL\"" >> "$HARDWARE_ENV_FILE"

# ─── Disk Detection ───────────────────────────────────────────────────────────
DISK_FREE_GB=$(df -BG . | tail -1 | awk '{print $4}' | tr -d 'G')
echo "Disk free: ${DISK_FREE_GB} GB on current volume"

if [ "$DISK_FREE_GB" -lt 50 ]; then
    echo "WARNING: Less than 50 GB free disk space. Minimum 50 GB recommended for model storage and document cache."
fi

echo "CIVICRECORDS_DISK_FREE_GB=$DISK_FREE_GB" >> "$HARDWARE_ENV_FILE"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "=== Detection Complete ==="
echo "Platform:        $PLATFORM"
echo "GPU Enabled:     $GPU_ENABLED"
if [ "$GPU_ENABLED" = true ]; then
    echo "GFX Override:    $HSA_OVERRIDE"
    echo "CU Count:        $GPU_CU_COUNT"
fi
echo "NPU Available:   $NPU_AVAILABLE (${NPU_TOPS} TOPS)"
echo "Recommended Model: $RECOMMENDED_MODEL"
echo ""
echo "Configuration written to $HARDWARE_ENV_FILE"
echo "This file will be merged into your Docker environment automatically."
