# CivicRecords AI — Windows Hardware Detection Script
# Detects AMD GPU/NPU capabilities and writes configuration
# Called by install.ps1 before docker compose up

$ErrorActionPreference = "Continue"
$HardwareEnvFile = ".env.hardware"

Write-Host ""
Write-Host "=== CivicRecords AI Hardware Detection ===" -ForegroundColor Cyan
Write-Host ""

$envLines = @(
    "# CivicRecords AI — Auto-detected hardware configuration",
    "# Generated by scripts/detect_hardware.ps1 on $(Get-Date)"
)

# ─── CPU Detection ────────────────────────────────────────────────────────────
$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$cpuName = $cpu.Name.Trim()
Write-Host "CPU: $cpuName"
$envLines += "CIVICRECORDS_CPU_MODEL=`"$cpuName`""

$platform = "unknown"
$npuTops = 0

switch -Regex ($cpuName) {
    "Ryzen AI (Max|MAX)" {
        $platform = "strix_halo"; $npuTops = 50
        Write-Host "Platform: AMD Ryzen AI Max (Strix Halo)" -ForegroundColor Green
    }
    "Ryzen AI \d+ \d+(HX|HS|U|H)" {
        $platform = "strix_krackan"; $npuTops = 50
        Write-Host "Platform: AMD Ryzen AI 300/400 (Strix Point / Gorgon Point)" -ForegroundColor Green
    }
    "Ryzen [579] 8\d{3}" {
        $platform = "hawk_point"; $npuTops = 16
        Write-Host "Platform: AMD Ryzen 8000 (Hawk Point)" -ForegroundColor Green
    }
    "Ryzen [579] 7\d{3}(H|U|HS)" {
        $platform = "phoenix"; $npuTops = 16
        Write-Host "Platform: AMD Ryzen 7000 Mobile (Phoenix)" -ForegroundColor Green
    }
    "Ryzen 9 (7945|8945)HX" {
        $platform = "dragon_range"; $npuTops = 0
        Write-Host "Platform: Dragon Range — no NPU, use discrete GPU" -ForegroundColor Yellow
    }
    "Ryzen [579] 9\d{3}" {
        $platform = "granite_ridge"; $npuTops = 0
        Write-Host "Platform: Ryzen 9000 Desktop — no iGPU, CPU inference only" -ForegroundColor Yellow
    }
    default {
        Write-Host "Platform: Unknown — defaulting to CPU inference" -ForegroundColor Yellow
    }
}

$envLines += "CIVICRECORDS_PLATFORM=`"$platform`""
$envLines += "CIVICRECORDS_NPU_TOPS=$npuTops"

# ─── RAM Detection ────────────────────────────────────────────────────────────
$ramKB = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
$ramGB = [math]::Round($ramKB / 1GB)
Write-Host "RAM: $ramGB GB"

if ($ramGB -lt 32) {
    Write-Host "ERROR: CivicRecords AI requires a minimum of 32 GB RAM. Found: $ramGB GB" -ForegroundColor Red
    exit 1
}

$recommendedModel = if ($ramGB -ge 48) { "gemma4:27b" } else { "gemma4:12b" }
$envLines += "CIVICRECORDS_TOTAL_RAM_GB=$ramGB"
$envLines += "CIVICRECORDS_RECOMMENDED_MODEL=`"$recommendedModel`""

# ─── GPU Detection ────────────────────────────────────────────────────────────
$gpuEnabled = $false
$useHostOllama = $false
$ollamaBaseUrl = "http://ollama:11434"

$amdGpu = Get-CimInstance Win32_VideoController | Where-Object {
    $_.Name -match "AMD|Radeon" -and $_.Name -notmatch "610M|Basic|Display"
}

if ($amdGpu) {
    $gpuName = $amdGpu[0].Name
    Write-Host "AMD GPU: $gpuName" -ForegroundColor Green

    $vramBytes = $amdGpu[0].AdapterRAM
    $vramGB = [math]::Round($vramBytes / 1GB)
    Write-Host "Reported VRAM: $vramGB GB"

    $umaWarningThreshold = switch ($platform) {
        "strix_halo"      { 16 }
        "strix_krackan"   { 8  }
        "hawk_point"      { 4  }
        "phoenix"         { 4  }
        default           { 2  }
    }

    if ($vramGB -lt $umaWarningThreshold) {
        Write-Host ""
        Write-Host "WARNING: Reported GPU memory ($vramGB GB) is below the recommended" -ForegroundColor Yellow
        Write-Host "threshold ($umaWarningThreshold GB) for your platform ($platform)." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To improve LLM inference performance:" -ForegroundColor Yellow
        Write-Host "  1. Restart your PC and enter BIOS/UEFI setup (usually Del or F2 on boot)" -ForegroundColor White
        Write-Host "  2. Look for: Advanced > AMD CBS > NBIO > UMA Frame Buffer Size" -ForegroundColor White
        Write-Host "     (exact path varies by motherboard/laptop OEM)" -ForegroundColor White
        Write-Host "  3. Set to: Auto or $umaWarningThreshold GB or higher" -ForegroundColor White
        Write-Host "  4. Save and reboot" -ForegroundColor White
        Write-Host ""
        Write-Host "Without this change, inference may be slow or unstable." -ForegroundColor Yellow
        Write-Host ""
    }

    $ollamaCmd = Get-Command ollama -ErrorAction SilentlyContinue

    if ($ollamaCmd) {
        Write-Host "Native Ollama found: $($ollamaCmd.Source)" -ForegroundColor Green
        $useHostOllama = $true
        $gpuEnabled = $true
        $ollamaBaseUrl = "http://host.docker.internal:11434"

        try {
            $null = Invoke-RestMethod -Uri "http://localhost:11434/api/tags" -TimeoutSec 3
            Write-Host "Ollama service is running on localhost:11434" -ForegroundColor Green
        } catch {
            Write-Host "Starting Ollama service..." -ForegroundColor Yellow
            Start-Process ollama -ArgumentList "serve" -WindowStyle Hidden
            Start-Sleep -Seconds 5
            try {
                $null = Invoke-RestMethod -Uri "http://localhost:11434/api/tags" -TimeoutSec 5
                Write-Host "Ollama service started" -ForegroundColor Green
            } catch {
                Write-Host "WARNING: Could not start Ollama service. GPU inference may not work." -ForegroundColor Yellow
                Write-Host "Run 'ollama serve' manually before starting CivicRecords AI." -ForegroundColor Yellow
                $gpuEnabled = $false
            }
        }

        Write-Host ""
        Write-Host "GPU INFERENCE PATH: Native Ollama (DirectML)" -ForegroundColor Green
        Write-Host "Docker containers will connect to: $ollamaBaseUrl" -ForegroundColor Cyan
        Write-Host "The 'ollama' Docker service will be disabled in this configuration." -ForegroundColor Cyan

    } else {
        Write-Host ""
        Write-Host "AMD GPU detected but native Ollama is NOT installed." -ForegroundColor Yellow
        Write-Host "Without native Ollama, Docker containers cannot access your GPU." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To enable GPU-accelerated inference:" -ForegroundColor Cyan
        Write-Host "  winget install Ollama.Ollama" -ForegroundColor White
        Write-Host "  OR download from: https://ollama.ai/download/windows" -ForegroundColor White
        Write-Host ""
        Write-Host "Continuing with in-container CPU inference (slower)." -ForegroundColor Yellow
        Write-Host "Re-run install.ps1 after installing Ollama to enable GPU acceleration." -ForegroundColor Yellow
        $useHostOllama = $false
        $gpuEnabled = $false
    }
} else {
    Write-Host "No AMD GPU detected or GPU is Radeon 610M (unsuitable for inference)" -ForegroundColor Yellow
    Write-Host "Inference will run on CPU only" -ForegroundColor Yellow
}

$envLines += "CIVICRECORDS_GPU_ENABLED=$($gpuEnabled.ToString().ToLower())"
$envLines += "CIVICRECORDS_USE_HOST_OLLAMA=$($useHostOllama.ToString().ToLower())"
$envLines += "OLLAMA_BASE_URL=`"$ollamaBaseUrl`""

# ─── NPU Detection ────────────────────────────────────────────────────────────
$npuAvailable = $false

$xdnaDevice = Get-PnpDevice -ErrorAction SilentlyContinue |
    Where-Object { $_.FriendlyName -match "XDNA|NPU|Ryzen AI" -and $_.Status -eq "OK" }

if ($xdnaDevice) {
    $npuAvailable = $true
    Write-Host "NPU: XDNA detected ($npuTops TOPS) — reserved for future ONNX integration" -ForegroundColor Cyan
} else {
    Write-Host "NPU: Not detected or driver not installed" -ForegroundColor Gray
    if ($npuTops -gt 0) {
        Write-Host "  Your CPU supports XDNA NPU ($npuTops TOPS) but the driver may not be installed." -ForegroundColor Gray
        Write-Host "  Install AMD NPU driver from: https://www.amd.com/en/support/downloads" -ForegroundColor Gray
    }
}

$envLines += "CIVICRECORDS_NPU_AVAILABLE=$($npuAvailable.ToString().ToLower())"

# ─── Disk Detection ───────────────────────────────────────────────────────────
$disk = Get-PSDrive -Name (Split-Path $PWD -Qualifier).TrimEnd(':') -ErrorAction SilentlyContinue
if ($disk) {
    $diskFreeGB = [math]::Round($disk.Free / 1GB)
    Write-Host "Disk free: $diskFreeGB GB"
    if ($diskFreeGB -lt 50) {
        Write-Host "WARNING: Less than 50 GB free. Minimum 50 GB recommended for models and document cache." -ForegroundColor Yellow
    }
    $envLines += "CIVICRECORDS_DISK_FREE_GB=$diskFreeGB"
}

# ─── Write .env.hardware ──────────────────────────────────────────────────────
$envLines | Set-Content -Path $HardwareEnvFile -Encoding UTF8

Write-Host ""
Write-Host "=== Detection Complete ===" -ForegroundColor Cyan
Write-Host "Platform:          $platform"
Write-Host "GPU Enabled:       $gpuEnabled"
Write-Host "Ollama URL:        $ollamaBaseUrl"
Write-Host "NPU Available:     $npuAvailable ($npuTops TOPS)"
Write-Host "Recommended Model: $recommendedModel"
Write-Host ""
Write-Host "Configuration written to $HardwareEnvFile" -ForegroundColor Green
